FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:10-run
RUN apt-get update && apt-get install -y curl wget build-essential libelf-dev awscli bc flex libssl-dev python bison
COPY . /usr/src/app
WORKDIR /usr/src/app
COPY package*.json ./

RUN apk add --no-cache --virtual .gyp python make g++ linux-headers && npm install && apk del .gyp

ENV VERSION '2.43.0+rev1.dev'
RUN ./build.sh %%BALENA_MACHINE_NAME%% $VERSION example_module

CMD ./run.sh


COPY . ./

ENV UDEV=on

CMD["npm", "start"]