FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:10-run
RUN apt-get update && apt-get install -y curl wget build-essential libelf-dev awscli bc flex libssl-dev python bison
COPY . /usr/src/app
WORKDIR /usr/src/app
COPY package*.json ./

RUN apt-get install -y .gyp python make g++ linux-headers && npm install

ENV VERSION '2.43.0+rev1.dev'
RUN ./build.sh %%BALENA_MACHINE_NAME%% $VERSION example_module

RUN ./run.sh


COPY . ./

ENV UDEV=on

CMD npm start